changelog:
  categories:
    - title: 🚀 New Features
      labels:
        - feature
        - enhancement
    - title: 🐛 Bug Fixes
      labels:
        - bug
        - bugfix
        - fix
    - title: 📝 Documentation
      labels:
        - documentation
        - docs
    - title: 🧹 Maintenance
      labels:
        - maintenance
        - chore
        - refactor
    - title: 🔧 Dependencies
      labels:
        - dependencies
        - deps
    - title: Other Changes
      labels:
        - "*"
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot