networks:
  redis-net:
    driver: bridge

services:
  redis:
    image: redislabs/client-libs-test:8.2
    container_name: redis
    ports:
      - "3000:3000"
    networks:
      - redis-net
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "3000", "PING"]
      interval: 10s
      timeout: 3s
      retries: 5

  resp-proxy:
    image: redislabs/client-resp-proxy
    container_name: resp-proxy
    environment:
      LISTEN_HOST: "0.0.0.0"
      LISTEN_PORT: "6379,6380,6381"
      TARGET_HOST: "redis"
      TARGET_PORT: "3000"
      API_PORT: "4000"
      ENABLE_LOGGING: true
      SIMULATE_CLUSTER: true
    ports:
      - "6379:6379"
      - "6380:6380"
      - "6381:6381"
      - "4000:4000"
    depends_on:
      - redis
    networks:
      - redis-net
    healthcheck:
      test: ["CMD", "sh", "-c", "wget -qO- http://localhost:4000/stats || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

  # debug:
  #   image: nicolaka/netshoot:latest
  #   container_name: debug
  #   depends_on:
  #     - resp-proxy
  #   networks:
  #     - redis-net
  #   command: sleep infinity
  #   stdin_open: true
  #   tty: true
